name: 'deploy dsmith-web'

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/dsmith-web*'
      - 'dsmith-web/**'
      - '!dsmith-web/**/*.md'

jobs:
  build_and_deploy:
    name: Build/Test/Deploy dsmith-web to Google Cloud Run
    runs-on: ubuntu-latest
    environment: production
    env:
      IMAGE_NAME: us-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/dsmith/web
    steps:
      - name: checkout dsmith repository
        uses: actions/checkout@v3

      - name: authenticate google cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{secrets.GCP_SVCACCT_KEY}}'

      - name: setup google cloud
        uses: google-github-actions/setup-gcloud@v0
        # with:
        #   project_id: ${{secrets.GCP_PROJECT_ID}}
        #   service_account_email: ${{secrets.GCP_SVCACCT_EMAIL}}
        #   service_account_key: ${{secrets.GCP_SVCACCT_KEY}}
        #   export_default_credentials: true
      
      - name: configure docker
        run: gcloud auth configure-docker us-docker.pkg.dev --quiet
      
      - name: build docker image
        run: docker build -f ./dsmith-web/dsmith-web.dockerfile -t $IMAGE_NAME ./dsmith-web

      - name: push docker image to Google Artifact Registry
        run: docker push $IMAGE_NAME

      - name: push container to Google Cloud Run (two regions)
        run: |
          gcloud run deploy web \
          --image $IMAGE_NAME \
          --region us-west1 \
          --platform managed \
          --allow-unauthenticated
          gcloud run deploy web \
          --image $IMAGE_NAME \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated